apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-0dxt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-0dxt
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-0dxt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-0dxt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-0dxt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wvnr-tenant/status-quarkus-io/statusquarkusio-0dxt@sha256:7d78f6abf2c879136f6b2e2aeebfbc153846ebb0341886130d20c4e3fd40771f
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
